apiVersion: v1
kind: Service
metadata:
  name: "$K8S_SERVICE_NAME-service"
  namespace: "$K8S_NAMESPACE"
  labels:
    app: "$K8S_SERVICE_NAME"
spec:
  ports:
    - port: $CONTAINER_PORT_1
  selector:
    app: "$K8S_SERVICE_NAME"